version: '2'
services:
  dev-rabbit:
    image: rabbitmq:3.9-management-alpine
    container_name: dev-rabbit
    hostname: localhost
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    shm_size: 256m
    ports:
      - "${RABBIT_SITE_PORT}:15672"
      - "${RABBIT_PORT}:5672"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      - relocan-dev-net
networks:
  relocan-dev-net:
    name: relocan-dev-net
    driver: bridge

    
